[package]
name = "bunnies"
version = "0.1.0"
edition = "2024"
description = "An ultra-fast chess move generation library."
authors = ["Vibhav Singamshetty <vibsingamshetty@gmail.com>"]
license = "MIT"
repository = "https://github.com/goodvibs/bunnies"
readme = "README.md"
keywords = ["chess", "fast", "move", "generation", "movegen"]
categories = ["games", "mathematics"]

[dependencies]
rand = "0.9.0"
indexmap = "2.2.5"
fastrand = "2.3.0"
static_init = "1.0.3"
logos = "0.15.0"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[test]]
name = "perft"

[[bench]]
name = "attack_generation"
harness = false