[package]
name = "bunnies"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.4"
rand_distr = "0.4.3"
serde = { version = "1.0.160", features = ["derive"] }
lazy_static = "1.4.0"
indexmap = "2.2.5"
bincode = "1.3.3"
fastrand = "2.1.1"
subenum = "1.1.2"
static_init = "1.0.3"