[package]
name = "bunnies"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.1"
serde = { version = "1.0.160", features = ["derive"] }
lazy_static = "1.4.0"
indexmap = "2.2.5"
bincode = "2.0.1"
fastrand = "2.1.1"
subenum = "1.1.2"
static_init = "1.0.3"